### ISSUE TITLE
Weight options for BOP, NetherEx, and BetterNether biomes.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Nether-API#12]
Images say all.

![2024-12-25_22 01 46](https://github.com/user-attachments/assets/397ac8b4-cf51-45fd-85fa-68f5ca83dadb)
![2024-12-25_22 01 49](https://github.com/user-attachments/assets/e12cfb77-b979-4182-b6f6-7c2af0674060)

**Comment by jbredwards** [comment]
Nether API only adds biome weight configs for the mods that don't offer it in their own configs (JITL, Nethercraft, and Stygian End). For any of the other mods (BOP, NetherEx, and BetterNether), you can adjust the biome weight settings through that mods' configs.

**Comment by MagmaSlime123** [comment]
BOP has no toggles.

**Comment by jbredwards** [comment]
> BOP has no toggles.

It does. Either set the "hell" weight to 0 or delete the "hell" entry for the biomes you want to disable. If you've never used the BOP biome configs before, here's an example of an `undergarden.json` file you can create inside of `config/biomesoplenty/biomes` to prevent the undergarden biome from generating:
```json
{
    "weights": {}
}
```

**Comment by MagmaSlime123** [comment]
I have no idea what goes in the {}.

**Comment by jbredwards** [comment]
> I have no idea what goes in the {}.

It's intentionally empty so the biome doesn't spawn, but you could put `{"hell": 0}` instead of `{}` if you prefer.

BOP biome configs basically contain all the modifications you want to make to the biome (you can view any biome's default settings in the `config/biomesoplenty/biomes/defaults` folder).
